version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - my-network

  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge